version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 017535066714.dkr.ecr.us-east-2.amazonaws.com
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build --platform linux/amd64 -t dea_p3_globalpartner .
      - docker tag dea_p3_globalpartner:latest 017535066714.dkr.ecr.us-east-2.amazonaws.com/dea_p3_globalpartner:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 017535066714.dkr.ecr.us-east-2.amazonaws.com/dea_p3_globalpartner:$IMAGE_TAG
      - echo Build completed successfully.

artifacts:
  files: []
